--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/LatamPMDevs/Commando
branches:
- pm5
projects:
  Commando:
    model: virion
    type: library
    lint:
      phpstan: false
    libs:
      - src: Muqsit/SimplePacketHandler/SimplePacketHandler
        version: ^0.1.3
...
